version: 2
updates:
  - package-ecosystem: npm
    directory: /platform
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - platform
    assignees:
      - Shashwat1319

  - package-ecosystem: npm
    directory: /agent
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - agent
    assignees:
      - Shashwat1319

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - ci
