export const TOP_DEVELOPERS: { username: string; name?: string }[] = [
  { username: 'torvalds', name: 'Linus Torvalds' },
  { username: 'karpathy', name: 'Andrej Karpathy' },
  { username: 'ggerganov', name: 'Georgi Gerganov' },
  { username: 'AUTOMATIC1111' },
  { username: 'oobabooga' },
  { username: 'comfyanonymous' },
  { username: 'camenduru' },
  { username: 'fchollet', name: 'François Chollet' },
  { username: 'ageron', name: 'Aurélien Géron' },
  { username: 'rasbt', name: 'Sebastian Raschka' },
  { username: 'Significant-Gravitas' },
  { username: 'AntonOsika' },
  { username: 'xtekky' },
  { username: 'binary-husky' },
  { username: 'danielmiessler', name: 'Daniel Miessler' },
  { username: 'yyx990803', name: 'Evan You' },
  { username: 'gaearon', name: 'Dan Abramov' },
  { username: 'sophiebits', name: 'Sophie Alpert' },
  { username: 'sebmarkbage', name: 'Sebastian Markbåge' },
  { username: 'acdlite', name: 'Andrew Clark' },
  { username: 'antfu', name: 'Anthony Fu' },
  { username: 'patak-dev' },
  { username: 'tj', name: 'TJ Holowaychuk' },
  { username: 'kentcdodds', name: 'Kent C. Dodds' },
  { username: 'wesbos', name: 'Wes Bos' },
  { username: 'taniarascia', name: 'Tania Rascia' },
  { username: 'joshwcomeau', name: 'Josh Comeau' },
  { username: 'thejameskyle', name: 'James Kyle' },
  { username: 'lukeed', name: 'Luke Edwards' },
  { username: 'paulmillr', name: 'Paul Miller' },
  { username: 'privatenumber', name: 'Hiroki Osame' },
  { username: 'egoist' },
  { username: 'adamwathan', name: 'Adam Wathan' },
  { username: 'steveruizok', name: 'Steve Ruiz' },
  { username: 'sindresorhus', name: 'Sindre Sorhus' },
  { username: 'paulirish', name: 'Paul Irish' },
  { username: 'addyosmani', name: 'Addy Osmani' },
  { username: 'developit', name: 'Jason Miller' },
  { username: 'mojombo', name: 'Tom Preston-Werner' },
  { username: 'mdo', name: 'Mark Otto' },
  { username: 'jeresig', name: 'John Resig' },
  { username: 'jashkenas', name: 'Jeremy Ashkenas' },
  { username: 'mbostock', name: 'Mike Bostock' },
  { username: 'substack', name: 'James Halliday' },
  { username: 'isaacs', name: 'Isaac Z. Schlueter' },
  { username: 'tobi', name: 'Tobi Lütke' },
  { username: 'evanw', name: 'Evan Wallace' },
  { username: 'fabpot', name: 'Fabien Potencier' },
  { username: 'dhh', name: 'DHH' },
  { username: 'matz', name: 'Yukihiro Matsumoto' },
  { username: 'antirez', name: 'Salvatore Sanfilippo' },
  { username: 'bradfitz', name: 'Brad Fitzpatrick' },
  { username: 'rakyll' },
  { username: 'rsc', name: 'Russ Cox' },
  { username: 'robpike', name: 'Rob Pike' },
  { username: 'mitchellh', name: 'Mitchell Hashimoto' },
  { username: 'mholt', name: 'Matt Holt' },
  { username: 'valyala' },
  { username: 'FiloSottile', name: 'Filippo Valsorda' },
  { username: 'davecheney', name: 'Dave Cheney' },
  { username: 'jvns', name: 'Julia Evans' },
  { username: 'kelseyhightower', name: 'Kelsey Hightower' },
  { username: 'mattn' },
  { username: 'QuincyLarson', name: 'Quincy Larson' },
  { username: 'jwasham', name: 'John Washam' },
  { username: 'octocat', name: 'GitHub Octocat' },
  { username: 'anuraghazra', name: 'Anurag Hazra' },
  { username: 'rahuldkjain', name: 'Rahul Jain' },
  { username: 'abhisheknaiidu', name: 'Abhishek Naidu' },
  { username: 'kothariji', name: 'Dhruv Kothari' },
  { username: 'trungdq88', name: 'Trung DQ' },
  { username: 'DenverCoder1', name: 'Jonah Lawrence' },
  { username: 'Ileriayo', name: 'Ileriayo Adebiyi' },
  { username: 'ashutosh00710', name: 'Ashutosh Kumar Singh' },
  { username: 'gautamkrishnar', name: 'Gautam Krishna R' },
  { username: 'lowlighter', name: 'Simon Lecoq' },
  { username: 'mishmanners', name: 'Mish Manners' },
  { username: 'kunal-kushwaha', name: 'Kunal Kushwaha' },
  { username: 'loveBabbar', name: 'Love Babbar' },
  { username: 'arpitbbhayani', name: 'Arpit Bhayani' },
  { username: 'tusharnankani', name: 'Tushar Nankani' },
  { username: 'DIYgod' },
  { username: 'imsyy' },
  { username: 'XIU2' },
  { username: 'jlord', name: 'Jessica Lord' },
  { username: 'ankane', name: 'Andrew Kane' },
  { username: 'sferik', name: 'Erik Michaels-Ober' },
];

export const HOMEPAGE_FAMOUS = [
  'torvalds',
  'karpathy',
  'ggerganov',
  'AUTOMATIC1111',
  'anuraghazra',
  'rahuldkjain',
  'kunal-kushwaha',
  'antfu',
];
