import type { NextApiRequest, NextApiResponse } from 'next';
import crypto from 'crypto';
import { rateLimit } from '../../lib/rate-limit';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN || '';
const headers: Record<string, string> = { Accept: 'application/vnd.github.v3+json' };
if (GITHUB_TOKEN) headers.Authorization = `Bearer ${GITHUB_TOKEN}`;

async function fetchJSON(url: string) {
  const res = await fetch(url, { headers });
  if (!res.ok) return null;
  return res.json();
}

function generateReadme(data: {
  username: string; avatar: string; name: string; bio: string;
  location: string; blog: string; company: string; twitter: string;
  totalRepos: number; totalStars: number; totalForks: number;
  languages: { name: string; percentage: number }[];
  topRepos: { name: string; description: string; stars: number; forks: number; language: string; url: string; topics: string[] }[];
  pinned: { name: string; description: string; stars: number; forks: number; language: string; url: string }[];
  recentActivity: string[];
  score: number;
}, style: string): string {
  const name = data.name || data.username;
  const twitterBadge = data.twitter ? `[![X](https://img.shields.io/twitter/follow/${data.twitter}?style=social)](https://x.com/${data.twitter})` : '';

  const statsBar = `<div align="center">
  <img src="https://img.shields.io/badge/Repos-${data.totalRepos}-blue?style=flat-square" />
  <img src="https://img.shields.io/badge/Stars-${data.totalStars}-yellow?style=flat-square" />
  <img src="https://img.shields.io/badge/Forks-${data.totalForks}-orange?style=flat-square" />
  <img src="https://custom-icon-badges.demolab.com/badge/AutoDev%20Score-${data.score}-brightgreen?logo=star&style=flat-square" />
</div>`;

  const langBar = data.languages.length > 0
    ? `\n${data.languages.map(l => `![${l.name}](https://img.shields.io/badge/${encodeURIComponent(l.name)}-${l.percentage}%25-${getLangColor(l.name)}?style=flat-square)`).join(' ')}\n`
    : '';

  const topReposSection = data.topRepos.length > 0
    ? `\n### 📌 Pinned Repositories\n\n${data.topRepos.map(r =>
      `#### [${r.name}](${r.url})\n${r.description}\n${r.topics.length > 0 ? `\`${r.topics.join('` `')}\`\n` : ''}⭐ ${r.stars} · 🍴 ${r.forks} · 🔧 ${r.language}`
    ).join('\n\n')}`
    : '';

  const pinnedSection = data.pinned.length > 0
    ? `\n### 📌 Pinned\n\n${data.pinned.map(r =>
      `[![${r.name}](https://github-readme-stats.vercel.app/api/pin/?username=${data.username}&repo=${r.name})](${r.url})`
    ).join('\n')}`
    : '';

  const activitySection = data.recentActivity.length > 0
    ? `\n### ⚡ Recent Activity\n\n${data.recentActivity.map(a => `- ${a}`).join('\n')}`
    : '';

  const scoreBadge = `[![AutoDev Score](https://img.shields.io/badge/AutoDev%20Score-${data.score}/100-${getScoreColor(data.score)}?style=for-the-badge)](https://autodev-kappa.vercel.app/dashboard?user=${data.username})`;

  const templates: Record<string, string> = {
    minimal: `# 👋 Hello, I'm ${name}${data.bio && data.bio !== 'No bio' ? `\n\n${data.bio}` : ''}

${statsBar}

${data.location ? `📍 ${data.location}` : ''} ${data.company ? `· 🏢 ${data.company}` : ''} ${data.blog ? `· 🔗 ${data.blog}` : ''}

${langBar}

---

${scoreBadge}
`,

    professional: `# ${name}

${statsBar}

${twitterBadge}

---

## 👨‍💻 About Me

${data.bio && data.bio !== 'No bio' ? `> ${data.bio}` : ''}

${data.location ? `- 🌍 **Location:** ${data.location}` : ''}
${data.company ? `- 🏢 **Company:** ${data.company}` : ''}
${data.blog ? `- 🔗 **Website:** [${data.blog}](${data.blog})` : ''}
- 📊 **GitHub:** [${data.username}](https://github.com/${data.username})

---

## 🛠️ Languages & Tools

${langBar}
${data.languages.length > 0 ? data.languages.map(l => `- **${l.name}** — ${l.percentage}% of repos`).join('\n') : ''}

${topReposSection}

${activitySection}

---

<div align="center">
  <i>Profile auto-generated by <a href="https://autodev-kappa.vercel.app">AutoDev</a></i>
</div>
`,

    recruiter: `# ${name}

${statsBar}

---

## 📋 Summary

${data.bio && data.bio !== 'No bio' ? `${data.bio}` : `${name} is a developer with ${data.totalRepos} public repositories and ${data.totalStars} stars across their projects.`}

${data.location ? `- 📍 **Based in:** ${data.location}` : ''}
${data.company ? `- 💼 **Currently:** ${data.company}` : ''}

---

## 📊 GitHub Statistics

| Metric | Value |
|--------|-------|
| Public Repositories | ${data.totalRepos} |
| Total Stars Earned | ${data.totalStars} |
| Repository Forks | ${data.totalForks} |
| AutoDev Score | ${data.score}/100 |

${langBar}

## 🔝 Top Projects

${data.topRepos.length > 0 ? `| # | Repository | Stars | Forks | Language |\n|---|------------|:----:|:----:|:--------:|\n${data.topRepos.map((r, i) => `| ${i + 1} | [${r.name}](${r.url}) | ${r.stars} | ${r.forks} | ${r.language} |`).join('\n')}` : ''}

${pinnedSection}

---

<div align="center">
  <i>Recruiter-ready profile · Generated by <a href="https://autodev-kappa.vercel.app">AutoDev</a></i>
  <br/>
  ${scoreBadge}
</div>
`,
  };

  return templates[style] || templates.professional;
}

function getLangColor(name: string): string {
  const colors: Record<string, string> = {
    JavaScript: '#f7df1e', TypeScript: '#3178c6', Python: '#3572A5',
    HTML: '#e34c26', CSS: '#563d7c', Rust: '#dea584', Go: '#00ADD8',
    Java: '#b07219', C: '#555555', 'C++': '#f34b7d', 'C#': '#178600',
    Ruby: '#701516', PHP: '#4F5D95', Swift: '#F05138', Kotlin: '#A97BFF',
    Dart: '#00B4AB', Lua: '#000080', Scala: '#c22d40', Shell: '#89e051',
    Vue: '#4fc08d', Svelte: '#ff3e00',
  };
  return colors[name] || '#666';
}

function getScoreColor(score: number): string {
  if (score >= 70) return 'brightgreen';
  if (score >= 40) return 'yellow';
  return 'red';
}

async function verifyPayment(payment_id: string, order_id: string, signature: string): Promise<boolean> {
  const keySecret = process.env.RAZORPAY_KEY_SECRET;
  const keyId = process.env.RAZORPAY_KEY_ID;
  if (!keySecret || !keyId) return false;

  const expected = crypto.createHmac('sha256', keySecret).update(`${order_id}|${payment_id}`).digest('hex');
  if (expected !== signature) return false;

  const auth = Buffer.from(`${keyId}:${keySecret}`).toString('base64');
  try {
    const payRes = await fetch(`https://api.razorpay.com/v1/payments/${payment_id}`, {
      headers: { Authorization: `Basic ${auth}` },
    });
    if (!payRes.ok) return false;
    const payment = await payRes.json();
    return payment.status === 'captured';
  } catch {
    return false;
  }
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const ip = req.headers['x-forwarded-for']?.toString().split(',')[0]?.trim() || req.headers['x-real-ip']?.toString() || 'unknown';
  const rl = rateLimit({ key: `generate-readme:${ip}`, maxRequests: 20, windowMs: 60000 });
  if (!rl.allowed) return res.status(429).json({ error: `Too many requests. Try again in ${Math.ceil(rl.resetIn / 1000)}s.` });

  const { username, style = 'professional', payment_id, order_id, razorpay_signature } = req.method === 'POST' ? req.body : req.query;

  if (!username || typeof username !== 'string') {
    return res.status(400).json({ error: 'Username is required' });
  }

  try {
    const [user, repos, events] = await Promise.all([
      fetchJSON(`https://api.github.com/users/${username}`),
      fetchJSON(`https://api.github.com/users/${username}/repos?per_page=100&sort=updated`),
      fetchJSON(`https://api.github.com/users/${username}/events/public?per_page=30`),
    ]);

    if (!user) return res.status(404).json({ error: 'User not found' });

    const repoList = Array.isArray(repos) ? repos : [];
    const eventList = Array.isArray(events) ? events : [];

    const totalStars = repoList.reduce((sum: number, r: any) => sum + (r.stargazers_count || 0), 0);
    const totalForks = repoList.reduce((sum: number, r: any) => sum + (r.forks_count || 0), 0);

    const langMap: Record<string, number> = {};
    repoList.forEach((r: any) => { if (r.language) langMap[r.language] = (langMap[r.language] || 0) + 1; });
    const totalLangs = Object.values(langMap).reduce((a: number, b: number) => a + b, 0);
    const languages = Object.entries(langMap)
      .map(([name, count]) => ({ name, percentage: Math.round((count / totalLangs) * 100) }))
      .sort((a, b) => b.percentage - a.percentage).slice(0, 8);

    const topRepos = repoList.filter((r: any) => !r.fork)
      .sort((a: any, b: any) => b.stargazers_count - a.stargazers_count)
      .slice(0, 5)
      .map((r: any) => ({
        name: r.name, description: r.description || 'No description',
        stars: r.stargazers_count || 0, forks: r.forks_count || 0,
        language: r.language || 'Unknown', url: r.html_url,
        topics: r.topics || [],
      }));

    const pinnedUrls: { name: string; description: string; stars: number; forks: number; language: string; url: string }[] = [];
    if (repoList.length > 0) {
      try {
        const pinnedRes = await fetch(`https://api.github.com/users/${username}/repos?sort=updated&per_page=6`, { headers });
        if (pinnedRes.ok) {
          const pinnedData = await pinnedRes.json();
          pinnedUrls.push(...pinnedData.filter((r: any) => !r.fork).slice(0, 3).map((r: any) => ({
            name: r.name, description: r.description || '', stars: r.stargazers_count || 0,
            forks: r.forks_count || 0, language: r.language || 'Unknown', url: r.html_url,
          })));
        }
      } catch {}
    }

    const recentActivity = eventList.slice(0, 5).map((e: any) => {
      const repo = e.repo?.name || 'unknown';
      switch (e.type) {
        case 'PushEvent': return `Pushed to [${repo}](https://github.com/${repo})`;
        case 'CreateEvent': return `Created ${e.payload?.ref_type || 'resource'} in [${repo}](https://github.com/${repo})`;
        case 'IssuesEvent': return `${e.payload?.action || 'Updated'} issue in [${repo}](https://github.com/${repo})`;
        case 'PullRequestEvent': return `${e.payload?.action || 'Updated'} PR in [${repo}](https://github.com/${repo})`;
        case 'ForkEvent': return `Forked [${repo}](https://github.com/${repo})`;
        case 'WatchEvent': return `Starred [${repo}](https://github.com/${repo})`;
        default: return `Activity in [${repo}](https://github.com/${repo})`;
      }
    }).filter(Boolean);

    const consistency = Math.min(100, Math.round(
      (repoList.length > 0 ? 30 : 0) + (totalStars > 0 ? 20 : 0) +
      (eventList.length > 10 ? 25 : eventList.length > 0 ? 10 : 0) +
      (user.public_repos > 5 ? 15 : 5) + (user.bio ? 10 : 0)
    ));
    const overallScore = Math.round((consistency + Math.min(100, totalStars * 2)) / 2);

    const readme = generateReadme({
      username: user.login, avatar: user.avatar_url, name: user.name || user.login,
      bio: user.bio || 'No bio', location: user.location || '', blog: user.blog || '',
      company: user.company || '', twitter: user.twitter_username || '',
      totalRepos: user.public_repos, totalStars, totalForks,
      languages, topRepos, pinned: pinnedUrls, recentActivity,
      score: overallScore,
    }, style as string);

    if (req.method === 'POST') {
      if (!payment_id || !order_id || !razorpay_signature) {
        return res.status(400).json({ error: 'Payment ID, Order ID, and signature are required' });
      }

      const isValid = await verifyPayment(payment_id as string, order_id as string, razorpay_signature as string);
      if (!isValid) {
        return res.status(402).json({ error: 'Payment verification failed. Please try again.' });
      }

      res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename="README-${username}.md"`);
      return res.status(200).send(readme);
    }

    res.status(200).json({ username: user.login, readme, style });
  } catch (err: any) {
    res.status(500).json({ error: err.message || 'Failed to generate README' });
  }
}
